"""Execution-control primitives shared by live and replayable harnesses."""

from .components import (
    BuiltComponent,
    ComponentIdentity,
    ComponentKind,
    ComponentManifest,
    LearnedArtifactIdentity,
)
from .context import RunContext, RunIdentity, call_with_optional_runtime
from .context_manager import (
    ContextAtomicityViolation,
    ContextBudget,
    ContextBudgetExceeded,
    ContextFailure,
    ContextIntent,
    ContextItem,
    ContextItemCategory,
    ContextManager,
    ContextPlan,
    DeterministicTokenEstimator,
    StructuredCompactorV1,
)
from .failure_injection import (
    FailureInjectingProviderExecutor,
    FailureInjectingToolRunner,
    FailureInjectionPlan,
)
from .memory import (
    FakeClock,
    InMemoryMemoryStore,
    MemoryKind,
    MemoryOperation,
    MemoryOperationType,
    MemoryPolicy,
    MemoryQuery,
    MemoryRecord,
    MemorySensitivity,
    MemorySnapshotIdentity,
    MemorySourceType,
    MemoryStatus,
    MemoryWriteRequest,
    SQLiteMemoryStore,
)
from .provider import (
    FakeProviderExecutor,
    OpenAICompatibleProviderExecutor,
    ProviderCallKind,
    ProviderExecutor,
    ProviderFailure,
    ProviderFailureKind,
    ProviderRequest,
    ProviderResponse,
    ProviderUsage,
    provider_request_fingerprint,
)
from .registry import (
    ComponentBuildContext,
    ComponentConstructionError,
    ComponentRegistry,
    ComponentRegistryError,
    DuplicateComponentError,
    UnknownComponentError,
)
from .replay import (
    RecordedProviderExchange,
    RecordedToolExchange,
    RecordingProviderExecutor,
    RecordingToolRunner,
    ReplayMetadata,
    ReplayProviderExecutor,
    ReplayToolRunner,
    read_provider_exchanges,
    read_tool_exchanges,
    write_provider_exchanges,
    write_tool_exchanges,
)
from .session import (
    InMemorySessionStore,
    SessionEvent,
    SessionEventType,
    SessionRecord,
    SessionRevisionConflictError,
    SQLiteSessionStore,
)

__all__ = [
    "BuiltComponent",
    "ComponentBuildContext",
    "ComponentConstructionError",
    "ComponentIdentity",
    "ComponentKind",
    "ComponentManifest",
    "ComponentRegistry",
    "ComponentRegistryError",
    "ContextAtomicityViolation",
    "ContextBudget",
    "ContextBudgetExceeded",
    "ContextFailure",
    "ContextIntent",
    "ContextItem",
    "ContextItemCategory",
    "ContextManager",
    "ContextPlan",
    "DeterministicTokenEstimator",
    "DuplicateComponentError",
    "FailureInjectingProviderExecutor",
    "FailureInjectingToolRunner",
    "FailureInjectionPlan",
    "FakeClock",
    "FakeProviderExecutor",
    "InMemoryMemoryStore",
    "InMemorySessionStore",
    "LearnedArtifactIdentity",
    "MemoryKind",
    "MemoryOperation",
    "MemoryOperationType",
    "MemoryPolicy",
    "MemoryQuery",
    "MemoryRecord",
    "MemorySensitivity",
    "MemorySnapshotIdentity",
    "MemorySourceType",
    "MemoryStatus",
    "MemoryWriteRequest",
    "OpenAICompatibleProviderExecutor",
    "ProviderCallKind",
    "ProviderExecutor",
    "ProviderFailure",
    "ProviderFailureKind",
    "ProviderRequest",
    "ProviderResponse",
    "ProviderUsage",
    "RecordedProviderExchange",
    "RecordedToolExchange",
    "RecordingProviderExecutor",
    "RecordingToolRunner",
    "ReplayMetadata",
    "ReplayProviderExecutor",
    "ReplayToolRunner",
    "RunContext",
    "RunIdentity",
    "SQLiteMemoryStore",
    "SQLiteSessionStore",
    "SessionEvent",
    "SessionEventType",
    "SessionRecord",
    "SessionRevisionConflictError",
    "StructuredCompactorV1",
    "UnknownComponentError",
    "call_with_optional_runtime",
    "provider_request_fingerprint",
    "read_provider_exchanges",
    "read_tool_exchanges",
    "write_provider_exchanges",
    "write_tool_exchanges",
]


def __getattr__(name: str):
    """Lazy-load builder symbols to avoid retrieval/runtime import cycles."""

    if name in {
        "RuntimeBuilder",
        "RuntimeBuildConfig",
        "RuntimeBuildError",
        "RuntimeComponents",
        "RuntimeProfile",
        "SessionAnswer",
        "default_component_registry",
        "default_runtime_profiles",
    }:
        from .builder import (
            RuntimeBuildConfig,
            RuntimeBuilder,
            RuntimeBuildError,
            RuntimeComponents,
            SessionAnswer,
            default_component_registry,
            default_runtime_profiles,
        )
        from .profile import RuntimeProfile

        return {
            "RuntimeBuilder": RuntimeBuilder,
            "RuntimeBuildConfig": RuntimeBuildConfig,
            "RuntimeBuildError": RuntimeBuildError,
            "RuntimeComponents": RuntimeComponents,
            "RuntimeProfile": RuntimeProfile,
            "SessionAnswer": SessionAnswer,
            "default_component_registry": default_component_registry,
            "default_runtime_profiles": default_runtime_profiles,
        }[name]
    raise AttributeError(name)
